const input=document.getElementById("textInput")
const output=document.getElementById("textOutput")
const stats=document.getElementById("stats")
const err=document.getElementById("error")
const toUpper=document.getElementById("toUpper")
const toLower=document.getElementById("toLower")
const toTitle=document.getElementById("toTitle")
const trimLines=document.getElementById("trimLines")
const compactSpaces=document.getElementById("compactSpaces")
const removeEmpty=document.getElementById("removeEmpty")
const dedupLines=document.getElementById("dedupLines")
const sortAsc=document.getElementById("sortAsc")
const sortDesc=document.getElementById("sortDesc")
const copyOut=document.getElementById("copyOut")
const clearAll=document.getElementById("clearAll")
const find=document.getElementById("find")
const replace=document.getElementById("replace")
const doReplace=document.getElementById("doReplace")
const useRegex=document.getElementById("useRegex")
const ci=document.getElementById("caseInsensitive")
function setOut(t){output.value=t||"";updateStats()}
function getIn(){return input.value||""}
function lines(t){return String(t||"").split(/\r?\n/)}
function updateStats(){const t=output.value||"";const ch=t.length;const ln=lines(t).length;const words=(t.trim()?t.trim().split(/\s+/).length:0);stats.textContent=`字符: ${ch} · 单词: ${words} · 行: ${ln}`}
function titleCase(s){return s.replace(/\w\S*/g,m=>m.charAt(0).toUpperCase()+m.slice(1).toLowerCase())}
toUpper.addEventListener("click",()=>{setOut(getIn().toUpperCase())})
toLower.addEventListener("click",()=>{setOut(getIn().toLowerCase())})
toTitle.addEventListener("click",()=>{setOut(titleCase(getIn()))})
trimLines.addEventListener("click",()=>{setOut(lines(getIn()).map(l=>l.replace(/^\s+|\s+$/g,"")).join("\n"))})
compactSpaces.addEventListener("click",()=>{setOut(getIn().replace(/\s{2,}/g," "))})
removeEmpty.addEventListener("click",()=>{setOut(lines(getIn()).filter(l=>l.trim().length>0).join("\n"))})
dedupLines.addEventListener("click",()=>{const seen=new Set();const out=lines(getIn()).filter(l=>{const k=l;if(seen.has(k))return false;seen.add(k);return true});setOut(out.join("\n"))})
sortAsc.addEventListener("click",()=>{setOut(lines(getIn()).slice().sort().join("\n"))})
sortDesc.addEventListener("click",()=>{setOut(lines(getIn()).slice().sort().reverse().join("\n"))})
copyOut.addEventListener("click",()=>{navigator.clipboard.writeText(output.value||"").then(()=>{}).catch(()=>{})})
clearAll.addEventListener("click",()=>{input.value="";setOut("");err.style.display="none";err.textContent=""})
doReplace.addEventListener("click",()=>{err.style.display="none";err.textContent="";const src=getIn();const f=find.value||"";const r=replace.value||"";if(!f){setOut(src);return}try{let res="";if(useRegex.checked){const flags=ci.checked?"gi":"g";const re=new RegExp(f,flags);res=src.replace(re,r)}else{if(ci.checked){const re=new RegExp(f.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"gi");res=src.replace(re,r)}else{res=src.split(f).join(r)}}setOut(res)}catch(e){err.style.display="block";err.textContent="替换失败"}})
setOut("")
