const STORAGE_KEYS={subjects:"marker.subjects",templates:"marker.templates",instances:"marker.instances",settings:"marker.settings"}
const DEFAULT_SUBJECTS=[{id:uid(),name:"语文"},{id:uid(),name:"数学"},{id:uid(),name:"英文"},{id:uid(),name:"妈妈牌作业"},{id:uid(),name:"体育打卡"},{id:uid(),name:"久趣"},{id:uid(),name:"其他"}]
let subjects=[],templates=[],instances=[],settings={}
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function todayStr(d=new Date()){const y=d.getFullYear(),m=(d.getMonth()+1).toString().padStart(2,"0"),dd=d.getDate().toString().padStart(2,"0");return `${y}-${m}-${dd}`}
function load(){try{subjects=JSON.parse(localStorage.getItem(STORAGE_KEYS.subjects)||"null")||DEFAULT_SUBJECTS}catch(e){subjects=DEFAULT_SUBJECTS}
 try{templates=JSON.parse(localStorage.getItem(STORAGE_KEYS.templates)||"null")||[]}catch(e){templates=[]}
 try{instances=JSON.parse(localStorage.getItem(STORAGE_KEYS.instances)||"null")||[]}catch(e){instances=[]}
 try{settings=JSON.parse(localStorage.getItem(STORAGE_KEYS.settings)||"null")||{}}catch(e){settings={}}}
function save(){localStorage.setItem(STORAGE_KEYS.subjects,JSON.stringify(subjects));localStorage.setItem(STORAGE_KEYS.templates,JSON.stringify(templates));localStorage.setItem(STORAGE_KEYS.instances,JSON.stringify(instances));localStorage.setItem(STORAGE_KEYS.settings,JSON.stringify(settings))}
function setActiveTab(tab){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.getElementById('today').style.display=tab==='today'?"block":"none";document.getElementById('calendar').style.display=tab==='calendar'?"block":"none";document.getElementById('report').style.display=tab==='report'?"block":"none";document.getElementById('manage').style.display=tab==='manage'?"block":"none";settings.activeTab=tab;save()}
function initNav(){const tabs=document.querySelectorAll('.tab');tabs.forEach(b=>{const tab=b.dataset.tab; if(tab==='manage'){b.addEventListener('click',openManageAuth)} else {b.addEventListener('click',()=>setActiveTab(tab))}});const initial=settings.activeTab==='manage'? 'today' : (settings.activeTab||'today');setActiveTab(initial)}
function renderSubjects(){const list=document.getElementById('subjectList');list.innerHTML='';subjects.forEach(s=>{const row=document.createElement('div');row.className='item';const name=document.createElement('div');name.textContent=s.name;const del=document.createElement('button');del.className='btn secondary';del.textContent='删除';del.onclick=()=>{subjects=subjects.filter(x=>x.id!==s.id);save();renderSubjects();refreshTplSubject()};row.appendChild(name);row.appendChild(del);list.appendChild(row)})}
function refreshTplSubject(){const sel=document.getElementById('tplSubject');sel.innerHTML='';subjects.forEach(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=s.name;sel.appendChild(o)})}
function ensureOtherSubject(){if(!subjects.some(s=>s.name==='其他')){subjects.push({id:uid(),name:'其他'});save()}}
function addSubject(){const name=document.getElementById('subjectName').value.trim();if(!name)return;subjects.push({id:uid(),name});document.getElementById('subjectName').value='';save();renderSubjects();refreshTplSubject()}
function parseDays(str){if(!str)return [];return str.split(',').map(x=>parseInt(x.trim(),10)).filter(x=>x>=1&&x<=7)}
function getSelectedDays(){return Array.from(document.querySelectorAll('.tpl-day:checked')).map(el=>parseInt(el.value,10))}
function addTemplate(){const subjectId=document.getElementById('tplSubject').value;const title=document.getElementById('tplTitle').value.trim();const repeat=document.getElementById('tplRepeat').value;const days=repeat==='custom'?getSelectedDays():[];const start=document.getElementById('tplStart').value||todayStr();const end=document.getElementById('tplEnd').value||'';const exceptions=(document.getElementById('tplExceptions').value||'').split(',').map(x=>x.trim()).filter(Boolean);const variantMode=document.getElementById('tplVariantMode').value;const variants=(document.getElementById('tplVariants').value||'').split(/\n+/).map(s=>s.trim()).filter(Boolean);if(!subjectId||!title)return;templates.push({id:uid(),subjectId,title,repeatRule:repeat,daysOfWeek:days,startDate:start,endDate:end||undefined,exceptions,variantMode,variants});save();renderTemplates()}
function renderTemplates(){const list=document.getElementById('tplList');list.innerHTML='';templates.forEach(t=>{const row=document.createElement('div');row.className='item';const name=document.createElement('div');const subj=subjects.find(s=>s.id===t.subjectId);const rule=t.repeatRule==='daily'?'每天':t.repeatRule==='weekdays'?'工作日':`星期:${(t.daysOfWeek||[]).join(',')}`;name.textContent=`${subj?subj.name:''} · ${t.title} · ${rule}`;const del=document.createElement('button');del.className='btn secondary';del.textContent='删除';del.onclick=()=>{templates=templates.filter(x=>x.id!==t.id);save();renderTemplates()};row.appendChild(name);row.appendChild(del);list.appendChild(row)})}
function ensureDefaultTemplates(){const today=todayStr();let created=0;subjects.forEach(s=>{const exists=templates.some(t=>t.subjectId===s.id);if(exists)return;const repeat=(s.name==="语文"||s.name==="数学"||s.name==="英文")?"weekdays":"daily";templates.push({id:uid(),subjectId:s.id,title:s.name,repeatRule:repeat,daysOfWeek:[],startDate:today,endDate:undefined,exceptions:[]});created++});if(created>0){save();renderTemplates();refreshTplSubject()}return created}
function inRange(date,t){if(t.startDate&&date<t.startDate)return false; if(t.endDate&&date>t.endDate)return false; if((t.exceptions||[]).includes(date))return false; return true}
function weekday(date){const d=new Date(date);let w=d.getDay();return w===0?7:w}
function shouldGenerateFor(date,t){if(!inRange(date,t))return false; if(t.repeatRule==='daily')return true; if(t.repeatRule==='weekdays')return weekday(date)<=5; if(t.repeatRule==='custom')return (t.daysOfWeek||[]).includes(weekday(date)); return false}
function instanceKey(date,templateId){return `${date}|${templateId}`}
function daysBetweenStr(a,b){const da=new Date(a+"T00:00:00");const db=new Date(b+"T00:00:00");const diff=db-da;return Math.floor(diff/86400000)}
function seedRandom(s){let h=0;for(let i=0;i<s.length;i++){h=(h*31+s.charCodeAt(i))>>>0}return (h%100000)/100000}
function chooseTitle(t,date){if(Array.isArray(t.variants)&&t.variants.length>0){const mode=t.variantMode||'rotate';if(mode==='rotate'){const idx=Math.abs(daysBetweenStr(t.startDate||todayStr(),date))%t.variants.length;return t.variants[idx]}else if(mode==='random'){const idx=Math.floor(seedRandom(`${t.id}-${date}`)*t.variants.length);return t.variants[idx]}}return t.title}
function ensureTodayGenerated(d=new Date()){const date=todayStr(d);let changed=false;templates.forEach(t=>{if(shouldGenerateFor(date,t)){const key=instanceKey(date,t.id);if(!instances.find(i=>i.key===key)){const pickedTitle=chooseTitle(t,date);instances.push({id:uid(),key,date,subjectId:t.subjectId,title:pickedTitle,status:'pending',templateId:t.id});changed=true}}});if(changed)save()}
function renderToday(){ensureTodayGenerated();const list=document.getElementById('todayList');list.innerHTML='';const date=todayStr();const items=instances.filter(i=>i.date===date).sort((a,b)=>a.status.localeCompare(b.status));items.forEach(i=>{const row=document.createElement('div');row.className='item';const subj=subjects.find(s=>s.id===i.subjectId);const label=document.createElement('div');label.textContent=`${subj?subj.name:''} · ${i.title}`;const chk=document.createElement('input');chk.type='checkbox';chk.checked=i.status==='done';chk.onchange=()=>{i.status=chk.checked?'done':'pending';i.doneAt=chk.checked?Date.now():undefined;save();renderToday();renderCalendar();renderReport()};const duration=document.createElement('select');duration.className='select';duration.style.maxWidth='140px';const opts=['',5,10,15,20,25,30,45,60,90,120];opts.forEach(v=>{const o=document.createElement('option');o.value=v.toString();o.textContent=v?`${v} 分钟`:'耗时(分钟)';duration.appendChild(o)});duration.value=(i.durationMin||'').toString();duration.onchange=()=>{const v=parseInt(duration.value,10);i.durationMin=isNaN(v)?undefined:v;save()};const noteBtn=document.createElement('button');noteBtn.className='btn secondary';noteBtn.textContent='备注';noteBtn.style.marginLeft='auto';const note=document.createElement('input');note.className='input';note.placeholder='备注';note.value=i.note||'';note.style.display='none';note.onchange=()=>{i.note=note.value;save()};noteBtn.onclick=()=>{note.style.display=note.style.display==='none'?'inline-flex':'none';if(note.style.display!=='none')note.focus()};row.appendChild(chk);row.appendChild(label);row.appendChild(duration);row.appendChild(noteBtn);row.appendChild(note);row.addEventListener('click',e=>{const t=e.target;const tag=(t.tagName||'').toLowerCase();const type=(t.type||'').toLowerCase();if(tag==='select'||(tag==='input'&&type!=='checkbox')||tag==='button')return;if(t===chk)return;chk.checked=!chk.checked;chk.dispatchEvent(new Event('change'))});list.appendChild(row)});const done=items.filter(i=>i.status==='done').length;const total=items.length;const summary=document.getElementById('todaySummary');summary.textContent=`完成 ${done}/${total}`;if(total===0){list.innerHTML='<div class="small">尚未配置任务模板。前往“管理”添加，或点击“生成今日任务”自动添加默认模板。</div>'}const bar=document.getElementById('todayProgressBar');if(bar){const rate=total?Math.round((done/total)*100):0;bar.style.width=rate+'%'}const goal=document.getElementById('goalChip');if(goal){if(typeof settings.dailyGoal==='number'&&settings.dailyGoal>0){const remain=Math.max(settings.dailyGoal-done,0);goal.textContent=`还需 ${remain} 项`}else{goal.textContent=`目标：完成 ${Math.max(done,total>0?done:0)}/${total||0} 项`}}}
function monthStart(d){return new Date(d.getFullYear(),d.getMonth(),1)}
function monthEnd(d){return new Date(d.getFullYear(),d.getMonth()+1,0)}
let currentMonth=new Date()
let calendarMode='month'
function renderCalendar(){const grid=document.getElementById('calendarGrid');const weekDetail=document.getElementById('weekDetail');grid.style.display=calendarMode==='month'?"grid":"none";weekDetail.style.display=calendarMode==='week'?"grid":"none";grid.innerHTML='';weekDetail.innerHTML='';if(calendarMode==='month'){const start=monthStart(currentMonth),end=monthEnd(currentMonth);document.getElementById('monthTitle').textContent=`${start.getFullYear()}年${(start.getMonth()+1)}月`;const headOffset=(start.getDay()||7)-1;for(let i=0;i<headOffset;i++){const c=document.createElement('div');c.className='cell heat-0';grid.appendChild(c)}for(let day=1;day<=end.getDate();day++){const ds=todayStr(new Date(start.getFullYear(),start.getMonth(),day));const dayEl=document.createElement('div');const dayItems=instances.filter(i=>i.date===ds);const total=dayItems.length;const done=dayItems.filter(i=>i.status==='done').length;const rate=total?Math.round((done/total)*5):0;dayEl.className=`cell heat-${rate}${ds===todayStr()?' today':''}`;dayEl.textContent=day.toString();dayEl.title=total?`完成 ${done}/${total}`:'无任务';dayEl.onclick=()=>{ensureGeneratedForDate(ds);setActiveTab('today');renderToday()};grid.appendChild(dayEl)}}else{const w=weekRange(new Date());document.getElementById('monthTitle').textContent=`本周 ${todayStr(w.start)} ~ ${todayStr(w.end)}`;const names=['周一','周二','周三','周四','周五','周六','周日'];for(let i=0;i<7;i++){const d=new Date(w.start);d.setDate(d.getDate()+i);const ds=todayStr(d);const items=instances.filter(x=>x.date===ds);const total=items.length;const done=items.filter(x=>x.status==='done').length;const rate=total?Math.round((done/total)*100):0;const row=document.createElement('div');row.className='week-row';const dayEl=document.createElement('div');dayEl.className='week-day';dayEl.textContent=names[i];const dateEl=document.createElement('div');dateEl.className='week-date';dateEl.textContent=ds;const barWrap=document.createElement('div');barWrap.className='week-progress';const bar=document.createElement('div');bar.className='bar';bar.style.width=rate+'%';barWrap.appendChild(bar);const text=document.createElement('div');text.className='small';text.textContent=total?`完成 ${done}/${total}`:'无任务';row.appendChild(dayEl);row.appendChild(dateEl);row.appendChild(barWrap);row.appendChild(text);weekDetail.appendChild(row)}}}
function ensureGeneratedForDate(date){let changed=false;templates.forEach(t=>{if(shouldGenerateFor(date,t)){const key=instanceKey(date,t.id);if(!instances.find(i=>i.key===key)){const pickedTitle=chooseTitle(t,date);instances.push({id:uid(),key,date,subjectId:t.subjectId,title:pickedTitle,status:'pending',templateId:t.id});changed=true}}});if(changed)save()}
function rangeDays(start,end){const s=new Date(start.getFullYear(),start.getMonth(),start.getDate());const e=new Date(end.getFullYear(),end.getMonth(),end.getDate());const out=[];for(let d=new Date(s);d<=e;d.setDate(d.getDate()+1))out.push(todayStr(d));return out}
function statsForRange(start,end){const dates=rangeDays(start,end);let assigned=0,completed=0;const bySubject=new Map();dates.forEach(ds=>{const dayItems=instances.filter(i=>i.date===ds);assigned+=dayItems.length;completed+=dayItems.filter(i=>i.status==='done').length;dayItems.forEach(i=>{const s=subjects.find(x=>x.id===i.subjectId);const key=s?s.name:'';const val=bySubject.get(key)||{assigned:0,completed:0};val.assigned++;if(i.status==='done')val.completed++;bySubject.set(key,val)})});const rate=assigned?Math.round((completed/assigned)*100):0;return {assigned,completed,rate,bySubject}}
function renderStatsEl(el,stats){const lines=[];lines.push(`完成率 ${stats.rate}%`);subjects.forEach(s=>{const v=stats.bySubject.get(s.name)||{assigned:0,completed:0};const r=v.assigned?Math.round((v.completed/v.assigned)*100):0;lines.push(`${s.name} ${r}% (${v.completed}/${v.assigned})`)});el.innerHTML=lines.map(x=>`<div>${x}</div>`).join('')}
function weekRange(d){const wd=(d.getDay()||7);const start=new Date(d);start.setDate(start.getDate()-(wd-1));const end=new Date(start);end.setDate(start.getDate()+6);return {start,end}}
function renderWeekDetailList(){const weekDetail=document.getElementById('weekDetail');if(!weekDetail||calendarMode!=='week')return;weekDetail.innerHTML='';const w=weekRange(new Date());const names=['周一','周二','周三','周四','周五','周六','周日'];for(let i=0;i<7;i++){const d=new Date(w.start);d.setDate(d.getDate()+i);const ds=todayStr(d);ensureGeneratedForDate(ds);const items=instances.filter(x=>x.date===ds);const section=document.createElement('details');section.open=false;const summary=document.createElement('summary');summary.textContent=`${names[i]} ${ds}（${items.filter(x=>x.status==='done').length}/${items.length}）`;section.appendChild(summary);const list=document.createElement('div');list.className='list';items.forEach(it=>{const r=document.createElement('div');r.className='item';const subj=subjects.find(s=>s.id===it.subjectId);const label=document.createElement('div');label.textContent=`${subj?subj.name:''} · ${it.title}`;const chk=document.createElement('input');chk.type='checkbox';chk.checked=it.status==='done';chk.onchange=()=>{it.status=chk.checked?'done':'pending';it.doneAt=chk.checked?Date.now():undefined;save();renderWeekDetailList();renderToday();renderReport()};r.appendChild(chk);r.appendChild(label);r.addEventListener('click',e=>{const t=e.target;const tag=(t.tagName||'').toLowerCase();const type=(t.type||'').toLowerCase();if(tag==='select'||(tag==='input'&&type!=='checkbox'))return;if(t===chk)return;chk.checked=!chk.checked;chk.dispatchEvent(new Event('change'))});list.appendChild(r)});section.appendChild(list);weekDetail.appendChild(section)}}
function renderReport(){const w=weekRange(new Date());const ws=statsForRange(w.start,w.end);renderStatsEl(document.getElementById('weekStats'),ws);const ms=statsForRange(monthStart(new Date()),monthEnd(new Date()));renderStatsEl(document.getElementById('monthStats'),ms);renderBadges(ms)}
function formatDateChip(d){const w=['日','一','二','三','四','五','六'];return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')} 周${w[d.getDay()]}`}
function weatherText(code){if(code===0)return'晴';if(code>=1&&code<=3)return'多云';if(code===45||code===48)return'雾';if((code>=51&&code<=57)||(code>=61&&code<=65)||(code>=80&&code<=82))return'雨';if((code>=71&&code<=75)||code===77||code===85||code===86)return'雪';if(code===95||code===96||code===97||code===99)return'雷暴';return'天气'}
function fetchWeather(lat,lon){const ctrl=new AbortController();const t=setTimeout(()=>{try{ctrl.abort()}catch(_){}} ,8000);fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current_weather=true&daily=weathercode,temperature_2m_max,temperature_2m_min&timezone=auto&forecast_days=2`,{signal:ctrl.signal}).then(r=>r.json()).then(j=>{clearTimeout(t);const cw=j.current_weather;const todayText=`${weatherText(cw.weathercode)} ${Math.round(cw.temperature)}°C`;const d=j.daily;let nextText='';if(d&&Array.isArray(d.weathercode)&&d.weathercode.length>1){const code=d.weathercode[1];const tmin=d.temperature_2m_min[1];const tmax=d.temperature_2m_max[1];nextText=`明天：${weatherText(code)} ${Math.round(tmin)}~${Math.round(tmax)}°C`}settings.weather={text:todayText,ts:Date.now()};settings.weather_next={text:nextText,ts:Date.now()};save();const el=document.getElementById('weatherChip');if(el)el.textContent=todayText;const el2=document.getElementById('weatherNextChip');if(el2)el2.textContent=nextText}).catch(()=>{clearTimeout(t);const el=document.getElementById('weatherChip');if(el)el.textContent='天气不可用';const el2=document.getElementById('weatherNextChip');if(el2)el2.textContent=''})}
function initDateWeather(){const dc=document.getElementById('dateChip');if(dc)dc.textContent=formatDateChip(new Date());try{navigator.geolocation.getCurrentPosition(pos=>{fetchWeather(pos.coords.latitude,pos.coords.longitude)},()=>{const el=document.getElementById('weatherChip');const el2=document.getElementById('weatherNextChip');if(settings.weather&&settings.weather.text){el.textContent=settings.weather.text} else if(el){el.textContent='天气未开启'} if(settings.weather_next&&settings.weather_next.text){el2.textContent=settings.weather_next.text} else if(el2){el2.textContent=''}})}catch(_){}}
function computeStreak(subjectId){let streak=0;let maxStreak=0;for(let offset=0;offset<180;offset++){const d=new Date();d.setDate(d.getDate()-offset);const ds=todayStr(d);const items=instances.filter(i=>i.date===ds&&i.subjectId===subjectId);const allDone=items.length>0&&items.every(i=>i.status==='done');if(allDone){streak++;maxStreak=Math.max(maxStreak,streak)}else{streak=0}}return {current:streak,max:maxStreak}}
function openBadgeModal(html){const m=document.getElementById('badgeModal');const c=document.getElementById('badgeModalContent');c.innerHTML=html;m.style.display='flex'}
function closeBadgeModal(){const m=document.getElementById('badgeModal');m.style.display='none'}
function bindBadgeModal(){const btn=document.getElementById('badgeModalClose');btn.onclick=closeBadgeModal}
function openManageAuth(){const m=document.getElementById('manageAuthModal');if(!m){setActiveTab('manage');return}const input=document.getElementById('managePass');const err=document.getElementById('manageAuthError');if(input)input.value='';if(err)err.textContent='';m.style.display='flex'}
function closeManageAuth(){const m=document.getElementById('manageAuthModal');if(m)m.style.display='none'}
function bindManageAuth(){const ok=document.getElementById('manageAuthConfirm');const cancel=document.getElementById('manageAuthCancel');const input=document.getElementById('managePass');const err=document.getElementById('manageAuthError');if(ok)ok.onclick=()=>{const v=(input&&input.value||'').trim();if(v==='0523'){closeManageAuth();setActiveTab('manage')}else{if(err)err.textContent='密码错误'}};if(cancel)cancel.onclick=closeManageAuth}
function renderBadges(ms){const wrap=document.getElementById('badges');wrap.innerHTML='';subjects.forEach(s=>{const st=computeStreak(s.id);if(st.current>=7){const b=document.createElement('span');b.className='chip chip-streak';const icon=document.createElement('span');icon.className='icon';icon.textContent='🔥';const text=document.createElement('span');text.textContent=`${s.name} 连续7天`;b.appendChild(icon);b.appendChild(text);b.onclick=()=>{const thresholds=[7,14,21];let next=thresholds.find(t=>st.current<t);if(!next)next=st.current+7;const remain=Math.max(0,next-st.current);openBadgeModal(`<div class="title" style="font-size:16px">${s.name} 连续打卡</div><div class="small">当前：${st.current} 天</div><div class="small">下一目标：${next} 天</div><div class="small">还需：${remain} 天</div>`)};wrap.appendChild(b)}else if(ms.bySubject.get(s.name)&&(ms.bySubject.get(s.name).assigned>0)){const r=Math.round((ms.bySubject.get(s.name).completed/ms.bySubject.get(s.name).assigned)*100);if(r>=90){const b=document.createElement('span');b.className='chip chip-medal';const icon=document.createElement('span');icon.className='icon';icon.textContent='🏅';const text=document.createElement('span');text.textContent=`${s.name} 月90%+`;b.appendChild(icon);b.appendChild(text);b.onclick=()=>{openBadgeModal(`<div class="title" style="font-size:16px">${s.name} 月度完成率</div><div class="small">当前：${r}%</div><div class="small">下一目标：100%</div>`)};wrap.appendChild(b)}}});if(!wrap.children.length){const p=document.createElement('span');p.className='badge-warn';p.textContent='暂无徽章';wrap.appendChild(p)}}
function exportData(){const data={subjects,templates,instances,settings};const out=document.getElementById('exportOut');out.textContent=JSON.stringify(data,null,2)}
function importData(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);subjects=Array.isArray(data.subjects)?data.subjects:subjects;templates=Array.isArray(data.templates)?data.templates:templates;instances=Array.isArray(data.instances)?data.instances:instances;settings=typeof data.settings==='object'&&data.settings?data.settings:settings;save();renderSubjects();refreshTplSubject();renderTemplates();renderToday();renderCalendar();renderReport()}catch(e){}}
 reader.readAsText(file)}
function renderExceptions(){const wrap=document.getElementById('tplExceptionsList');wrap.innerHTML='';const arr=(document.getElementById('tplExceptions').value||'').split(',').map(x=>x.trim()).filter(Boolean);arr.forEach(ds=>{const chip=document.createElement('span');chip.className='badge';chip.textContent=ds;chip.title='点击删除';chip.onclick=()=>{const next=arr.filter(x=>x!==ds);document.getElementById('tplExceptions').value=next.join(',');renderExceptions()};wrap.appendChild(chip)})}
function bindManage(){document.getElementById('addSubjectBtn').onclick=addSubject;document.getElementById('addTplBtn').onclick=addTemplate;document.getElementById('exportBtn').onclick=exportData;document.getElementById('importFile').onchange=e=>{const f=e.target.files&&e.target.files[0];if(f)importData(f)};const repeatSel=document.getElementById('tplRepeat');repeatSel.addEventListener('change',()=>{document.getElementById('tplDaysGroup').style.display=repeatSel.value==='custom'?"flex":"none"});document.getElementById('tplDaysGroup').style.display=repeatSel.value==='custom'?"flex":"none";document.getElementById('addExceptionBtn').onclick=()=>{const d=document.getElementById('tplExceptionDate').value; if(!d) return; const cur=(document.getElementById('tplExceptions').value||'').split(',').map(x=>x.trim()).filter(Boolean); if(!cur.includes(d)){cur.push(d); document.getElementById('tplExceptions').value=cur.join(',');} renderExceptions()};document.getElementById('tplExceptions').addEventListener('input',renderExceptions);renderExceptions();const dg=document.getElementById('dailyGoal');const saveGoal=document.getElementById('saveGoalBtn');if(dg)dg.value=(typeof settings.dailyGoal==='number'&&settings.dailyGoal>0)?String(settings.dailyGoal):'';if(saveGoal)saveGoal.onclick=()=>{const v=parseInt(dg.value,10);settings.dailyGoal=isNaN(v)||v<0?undefined:v;save();renderToday()}}
function bindCalendar(){document.getElementById('prevMonthBtn').onclick=()=>{currentMonth.setMonth(currentMonth.getMonth()-1);renderCalendar();renderWeekDetailList()};document.getElementById('nextMonthBtn').onclick=()=>{currentMonth.setMonth(currentMonth.getMonth()+1);renderCalendar();renderWeekDetailList()};const mBtn=document.getElementById('monthViewBtn');const wBtn=document.getElementById('weekViewBtn');mBtn.onclick=()=>{calendarMode='month';mBtn.classList.add('active');wBtn.classList.remove('active');renderCalendar();renderWeekDetailList()};wBtn.onclick=()=>{calendarMode='week';wBtn.classList.add('active');mBtn.classList.remove('active');renderCalendar();renderWeekDetailList()}}
function bindToday(){document.getElementById('genTodayBtn').onclick=()=>{let created=0;created=ensureDefaultTemplates();ensureTodayGenerated();renderToday();renderCalendar();renderReport();if(created>0){const summary=document.getElementById('todaySummary');summary.textContent='已为缺失科目添加默认模板并生成今日任务'}};const qs=document.getElementById('quickSubject');const qt=document.getElementById('quickTitle');const qbtn=document.getElementById('addQuickBtn');const tl=document.getElementById('titleList');const qwrap=document.getElementById('quickAddWrap');const tgl=document.getElementById('toggleQuickBtn');function refreshQuickSubjects(){if(!qs)return;qs.innerHTML='';subjects.forEach(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=s.name;qs.appendChild(o)});}function titlesForSubject(sid){const set=new Set();templates.filter(t=>t.subjectId===sid).forEach(t=>set.add(t.title));instances.filter(i=>i.subjectId===sid).forEach(i=>set.add(i.title));return Array.from(set)}function refreshTitleList(){if(!qs||!tl)return;tl.innerHTML='';const arr=titlesForSubject(qs.value);arr.forEach(t=>{const o=document.createElement('option');o.value=t;tl.appendChild(o)})}function openQuick(){if(qwrap)qwrap.style.display='flex';refreshQuickSubjects();refreshTitleList()}function closeQuick(){if(qwrap)qwrap.style.display='none'}if(qs){refreshQuickSubjects();refreshTitleList();qs.onchange=refreshTitleList}if(qbtn){qbtn.onclick=()=>{const sid=qs?qs.value:'';const title=(qt?qt.value:'').trim();if(!sid||!title)return;const date=todayStr();const exist=instances.find(i=>i.date===date&&i.subjectId===sid&&i.title===title);if(!exist){instances.push({id:uid(),date,subjectId:sid,title,status:'pending'});save();renderToday();renderCalendar();renderReport();if(qt)qt.value='';refreshTitleList();closeQuick()}}}if(tgl){tgl.onclick=()=>{if(!qwrap)return;const vis=window.getComputedStyle(qwrap).display!=='none';if(vis)closeQuick();else openQuick()}}}
function init(){load();ensureOtherSubject();initNav();renderSubjects();refreshTplSubject();renderTemplates();bindManage();bindCalendar();bindToday();bindBadgeModal();bindManageAuth();initDateWeather();renderToday();renderCalendar();renderWeekDetailList();renderReport()}
document.addEventListener('DOMContentLoaded',init)
