const grid=document.getElementById("grid")
const search=document.getElementById("search")
const tagFilter=document.getElementById("tagFilter")
const statusFilter=document.getElementById("statusFilter")
const clearBtn=document.getElementById("clearFilterBtn")
const summaryEl=document.getElementById("filterSummary")
function render(list){grid.innerHTML="";list.forEach(t=>{const a=document.createElement("a");const enabled=!!t.path;a.className="card"+(enabled?"":" disabled");if(enabled)a.href=t.path;a.setAttribute('aria-label', t.name);const name=document.createElement("div");name.className="name";name.textContent=t.name;const desc=document.createElement("div");desc.className="desc";desc.textContent=t.desc+(enabled?"":" · 即将开放");a.appendChild(name);a.appendChild(desc);const tags=document.createElement("div");tags.className="row";if(Array.isArray(t.tags))t.tags.forEach(tag=>{const b=document.createElement("span");b.className="badge";b.textContent=tag;tags.appendChild(b)});a.appendChild(tags);grid.appendChild(a)})}
function getAllTags(){const src=Array.isArray(window.TOOLS_MANIFEST)?window.TOOLS_MANIFEST:[];const set=new Set();src.forEach(t=>Array.isArray(t.tags)&&t.tags.forEach(tag=>set.add(tag)));return Array.from(set).sort()}
function filter(q,tag,status){const s=(q||"").toLowerCase();const src=Array.isArray(window.TOOLS_MANIFEST)?window.TOOLS_MANIFEST:[];return src.filter(t=>{const txt=[t.name,t.desc].concat(t.tags||[]).join(" ").toLowerCase();const matchText=!s||txt.includes(s);const matchTag=!tag||tag==='__all__'||(Array.isArray(t.tags)&&t.tags.includes(tag));const enabled=!!t.path;const matchStatus=!status||status==='__all_status'||(status==='enabled'?enabled:!enabled);return matchText&&matchTag&&matchStatus})}
function syncURL(){const params=new URLSearchParams();const q=(search.value||"").trim();const tag=tagFilter.value;const status=statusFilter.value; if(q)params.set('q',q); if(tag&&tag!=='__all__')params.set('tag',tag); if(status&&status!=='__all_status')params.set('status',status);const qs=params.toString();const url=qs?`${location.pathname}?${qs}`:`${location.pathname}`;history.replaceState(null,'',url)}
function renderSummary(){const parts=[];const q=(search.value||"").trim();const tag=tagFilter.value;const status=statusFilter.value;const current=filter(q,tag,status);const count=current.length;parts.push(`<span class="badge">结果：${count}</span>`);if(q)parts.push(`<span class="badge">关键词：${q}</span>`);if(tag&&tag!=='__all__')parts.push(`<span class="badge">标签：${tag}</span>`);if(status&&status!=='__all_status')parts.push(`<span class="badge">状态：${status==='enabled'?'已开放':'即将开放'}</span>`);
  const tagMap=new Map();current.forEach(t=>Array.isArray(t.tags)&&t.tags.forEach(x=>tagMap.set(x,(tagMap.get(x)||0)+1)));const tagItems=Array.from(tagMap.entries()).sort((a,b)=>b[1]-a[1]).slice(0,8);
  const tagBar=tagItems.length?('<div class="row">'+tagItems.map(([name,val])=>`<span class="badge" data-tag="${name}">${name} · ${val}</span>`).join(' ')+'</div>'):'';
  summaryEl.innerHTML=`<div class="row">${parts.join(' ')}</div>${tagBar}`
}
function init(){const tags=getAllTags();tagFilter.innerHTML=['<option value="__all__">全部标签</option>',...tags.map(t=>`<option value="${t}">${t}</option>`)].join('');statusFilter.innerHTML='<option value="__all_status">全部状态</option><option value="enabled">已开放</option><option value="disabled">即将开放</option>';const qp=new URLSearchParams(location.search);const q=qp.get('q')||"";const tag=qp.get('tag')||'__all__';const status=qp.get('status')||'__all_status';search.value=q; if(Array.from(tagFilter.options).some(o=>o.value===tag)) tagFilter.value=tag; if(Array.from(statusFilter.options).some(o=>o.value===status)) statusFilter.value=status;render(filter(search.value||"",tagFilter.value,statusFilter.value));renderSummary();search.addEventListener("input",()=>{render(filter(search.value||"",tagFilter.value,statusFilter.value));syncURL();renderSummary()});tagFilter.addEventListener('change',()=>{render(filter(search.value||"",tagFilter.value,statusFilter.value));syncURL();renderSummary()});statusFilter.addEventListener('change',()=>{render(filter(search.value||"",tagFilter.value,statusFilter.value));syncURL();renderSummary()});
  grid.addEventListener('click',(e)=>{const b=e.target.closest('.badge');if(!b)return;const tagName=b.textContent.trim();if(Array.from(tagFilter.options).some(o=>o.value===tagName)){tagFilter.value=tagName;render(filter(search.value||"",tagFilter.value,statusFilter.value));syncURL();renderSummary()}})
  summaryEl.addEventListener('click',(e)=>{const b=e.target.closest('[data-tag]');if(!b)return;const tagName=b.getAttribute('data-tag');if(Array.from(tagFilter.options).some(o=>o.value===tagName)){tagFilter.value=tagName;render(filter(search.value||"",tagFilter.value,statusFilter.value));syncURL();renderSummary()}})
  clearBtn.addEventListener('click',()=>{search.value='';tagFilter.value='__all__';statusFilter.value='__all_status';render(filter('',tagFilter.value,statusFilter.value));syncURL();renderSummary()})
}
init()
